### ISSUE TITLE
I am trying to use this library in my Project. Can we create 2 listeners for front and back camera? I am trying to detect faces from both cameras simultaneously.

### ISSUE THREAD

**Issue by AkshayKajale** [darwinfrancis/viola#14]

**Comment by darwinfrancis** [comment]
Hi @AkshayKajale 
This library is not dealing with camera API at all. It takes bitmap image as input, process and respond back with result via callback.

The input image from both front and back camera will work well with this library. 

Please check sample apk provide with the repository to get better understanding of the library.
