### ISSUE TITLE
Proguard rules and R8

### ISSUE THREAD

**Issue by bassil-altamimi** [darwinfrancis/viola#8]
can you please share the Proguard rules and R8 for this library!

**Comment by darwinfrancis** [comment]
Hi @bassil-altamimi 

There is no additional proguard or R8 rule is required for this library to function.
I haven't tested it with minify enabled , but it is supposed to work without any additional proguard rules.

If you don't mind, please let me know your findings when proguard rules are enabled on application side.

**Comment by bassil-altamimi** [comment]
HI @darwinfrancis 

it's working fine with minify enabled feature.
